name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      # Build React App
      - name: Build React App
        env:
          VITE_SUPABASE_URL: https://zpxasdfhrwpxdswywrmr.supabase.co
          VITE_SUPABASE_PUBLISHABLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpweGFzZGZocndweGRzd3l3cm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NjQyNzIsImV4cCI6MjA4NjE0MDI3Mn0.zMalp1qNzeLKoUXAKwFnkrmn2awrYoQ7kgj-LPh39I4
          VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpweGFzZGZocndweGRzd3l3cm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NjQyNzIsImV4cCI6MjA4NjE0MDI3Mn0.zMalp1qNzeLKoUXAKwFnkrmn2awrYoQ7kgj-LPh39I4
        run: npm run build -- --emptyOutDir=false
      
      # Ensure the assets directory exists
      - name: Create Assets Directory
        run: mkdir -p android/app/src/main/assets/

      # Copy built files to Android assets
      - name: Copy Dist to Assets
        run: cp -r dist/* android/app/src/main/assets/

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.2'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Build Release APK
        env:
          Simple_KEYSTORE_PATH: "release.keystore"
          Simple_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          Simple_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          Simple_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          cd android
          gradle assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
